### ISSUE TITLE
document what shell scripts check_dup_gribtable.sh and check_gribdat.sh are for

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/wgrib2#173]
We have:

 ```
 -rwxrwxr-x  1 ed ed    404 Mar 29 09:57 check_dup_gribtable.sh
  -rwxrwxr-x  1 ed ed    204 Mar 29 09:57 check_gribdat.sh
```

What are these scripts for?

Do they need to be installed?

Are these test scripts? Or part of normal wgrib2 operation?

Also,` same questions for the following:

- create_tables.sh
- function.sh
- make_gribtable.sh

**Comment by webisu** [comment]
Wgrib2 has scripts that read the grib tables from NCEP, and ECMWF.  The
NCEP tables have to be manually checked
before adding them to wgrib2.  The biggest problem is they add new names
that are duplicates of old names
with different units.  (It is fine if a locally defined field has the same
name as a WMO defined field with the same units
because it takes time for WMO to define new fields.)

These are test scripts that are run when updating the grib2 table from the
NCO web pages.

**Comment by edwardhartnett** [comment]
Can we move all these scripts to their own subdirectory?

Also these should not be installed on WCOSS2.

**Comment by edwardhartnett** [comment]
We will defer the moving of any shell scripts pending further discussion.

I will document the purpose of these scripts in the scripts. PR shortly...
