### ISSUE TITLE
CMake support for unusual platforms vs gnu make?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/wgrib2#215]
Mentioned here: https://www.cpc.ncep.noaa.gov/products/wesley/wgrib2/

There is no platform that cannot build CMake from source which would be able to build wgrib2 from source.

Also, wgrib2 now requires ip-5.1.0, which also requires CMake.

CMake is supported on all know platforms of interest to NOAA. We do not have the resources to support all platforms, so if there really is a platform out there that uses wgrib2 but not cmake, then they will have to just stick with the last wgrib2 legacy release.

**Comment by webisu** [comment]
The old wgrib2 has flexible.  If you didn't have CMake, you could build
it without the libraries that required CMake.  If autoconfig didn't work
because you were cross compiling, you could select the libraries that
didn't use autoconfig.  Sure you lost some functionality but you got the
core functionality.

Nobody expects support for weird platforms.   NOAA produces grib files
for the public.  The public needs to be able to read the grib files.
If NOAA software doesn't support most platforms, Copernicus will
support the ECMWF products and software on these platforms.
NOAA will fall further back in mindshare.

**Comment by edwardhartnett** [comment]
We are not supporting a makefile build. Nor does anyone else with any other scientific software package.

**Comment by webisu** [comment]
We are on cmake.  The support for unusual platforms will be in how to
get the original software.  For example  to install aec, I did

    sudo apt install libaec-dev

This only works if libaec-dev exists for the system in question.  If it
doesn't
we have to have a URL to download the aec source code.

I tried to get jasper working on Ubuntu.  I didn't find a precompiled jasper
library.  So I would have to find the correct URL for the jasper library.

I am sure that finding the correct png library will be a problem.  Wgrib2 is
using an old but supported branch of pnglib. (v1.2.xx). I haven't checked
what changes are needed to support png v1.6.xx.
