### ISSUE TITLE
Error building on MacOSX: "ld: library 'tiff' not found"

### ISSUE THREAD

**Issue by mikeobr** [NOAA-EMC/wgrib2#265]
Hello! I am following the compilation instructions here: https://www.cpc.ncep.noaa.gov/products/wesley/wgrib2/compile_questions.html. I've edited the make file as suggested (setting compilers and disabling proj).

I am on MacOS Sonoma 14.4  and my versions of gcc and gfortran
```
$ gcc --version
gcc-14 (Homebrew GCC 14.2.0) 14.2.0
$ gfortran --version
GNU Fortran (Homebrew GCC 14.2.0) 14.2.0
```

However when running make I run into an error

```
[ 75%] Linking C executable ../../../bin/opj_decompress
ld: warning: ignoring duplicate libraries: '-ljpeg', '-llcms2', '-llzma', '-ltiff', '-lz', '-lzstd', '/opt/homebrew/grib2/lib/libz.a'
ld: library 'tiff' not found
collect2: error: ld returned 1 exit status
make[3]: *** [bin/opj_decompress] Error 1
make[2]: *** [src/bin/jp2/CMakeFiles/opj_decompress.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [/opt/homebrew/grib2/lib/libopenjp2.a] Error 2
```

Further up the log I see that it says it had found tiff
```
-- Found TIFF: /opt/homebrew/lib/libtiff.dylib (found version "4.7.0")
-- Your system seems to have a TIFF lib available, we will use it
```

Any pointers on what the issue might be here?

**Comment by webisu** [comment]
NOAA-EMC/wgrib2 is for support of the github version of wgrib2 and not the
makefile
version (v3.1.3 and older).

The problem is that the MacOS compatibility was done by the other developer
of pywgrib2.
Over the years, various people have blogs on how to compile wgrib2 for
MacOS.
All that I know is that you need  the real gnu gcc and gfortran.

The reference to src/bin/jp2/CMakeFiles makes me think that you are using
OpenJPEG.
Try using Jasper instead.  I suspect the MacOS build was tested using
Jasper.
If that doesn't work, try getting wgrib2 to compile without OpenJPEG and
Jasper.

I can use the github version to build a usable version of wgrib2 under
Ubuntu.  Not
all options work but I can send you my build notes.  Not sure whether that
will help
you with MacOS.

**Comment by mikeobr** [comment]
Apologies about going to the wrong place!

 I ended up getting it to build by setting
 
 ```
 USE_PNG=0
```

**Comment by mikeobr** [comment]
Closing, for any future explorers, the things I had set in my makefile were:

```
export CC=gcc
export FC=gfortran

USE_PROJ4=0
USE_PNG=0
```
