### ISSUE TITLE
Do a v2.0.8-cmake-v6 release

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/wgrib2#43]
@kgerheiser you just did a release?

Please follow the release steps here:
https://github.com/NOAA-EMC/NCEPLIBS/issues/172

In GitHub call the release "Version x.y.z"

Put together Release Notes patterns on what is in NCEPLIBS-sp.

This repo has no VERSION file, where does the version live? In the CMakeLists.txt file?

**Comment by kgerheiser** [comment]
The issue with wgrib2 is that we don't maintain the "master" source code.

The code is version 2.0.8 that Wesley released, but with a CMake build. I don't want to say I'm going to release version 2.0.9 and step ahead of the official release version because that will create confusion. T

For this repository I picked a version scheme of `vx.y.z-cmake-va`, where `a` is the CMake build revision and `x.y.z` is the official version of the code it's based on.

I know it's not ideal, but if you have a better scheme in mind I'm all for it.

**Comment by edwardhartnett** [comment]
OK, we have decided to name wgrib2 versions as @kgerheiser suggests. Otherwise we will follow the standard release procedure.

I have edit the release notes for the release, created the draft for next release, and created a GitHub project board for the next release.
